export default {
	FORM_ERRORS: 'FORM_ERRORS',
	GET_PRODUCTS: 'GET_PRODUCTS',
	ADD_STORE: 'ADD_STORE',
	ADD_DISTRIBUTOR: 'ADD_DISTRIBUTOR',
	GET_STORE_TYPES: 'GET_STORE_TYPES',
	GET_CATEGORIES: 'GET_CATEGORIES',
	GET_COUNT_BIES: 'GET_COUNT_BIES',
	GET_DISTRIBUTORS: 'GET_DISTRIBUTORS',
	DELETE_DISTRIBUTOR: 'DELETE_DISTRIBUTOR',
	EDIT_DISTRIBUTOR: 'EDIT_DISTRIBUTOR'
}