export default {
	FORM_ERRORS: 'FORM_ERRORS',
	
	GET_PRODUCTS: 'GET_PRODUCTS',
	GET_PREPPED_PRODUCTS: 'GET_PREPPED_PRODUCTS',
	GET_PRODUCT: 'GET_PRODUCT',
	GET_STORE_TYPES: 'GET_STORE_TYPES',
	GET_CATEGORIES: 'GET_CATEGORIES',
	GET_COUNT_BIES: 'GET_COUNT_BIES',
	GET_DISTRIBUTORS: 'GET_DISTRIBUTORS',
	GET_LOCATIONS: 'GET_LOCATIONS',
	GET_REMOVED_STORE_GOODS: 'GET_REMOVED_STORE_GOODS',
	GET_STORE_GOODS: 'GET_STORE_GOODS',
	GET_STORE: 'GET_STORE',
	GET_INVENTORY: 'GET_INVENTORY',
	GET_STORE_INVENTORY: 'GET_STORE_INVENTORY',
	GET_ORDERS: 'GET_ORDERS',
	GET_INVENTORY_ORDER: 'GET_INVENTORY_ORDER',
	GET_STORE_ORDERS: 'GET_STORE_ORDERS',
	GET_STORES: 'GET_STORES',

	EDIT_DISTRIBUTOR: 'EDIT_DISTRIBUTOR',	
	EDIT_PRODUCT: 'EDIT_PRODUCT',
	EDIT_STORE_GOOD: 'EDIT_STORE_GOOD',
	EDIT_PREPPED_PRODUCT: 'EDIT_PREPPED_PRODUCT',
	EDIT_INVENTORY: 'EDIT_INVENTORY',

	ADD_STORE: 'ADD_STORE',
	ADD_DISTRIBUTOR: 'ADD_DISTRIBUTOR',
	ADD_LOCATION: 'ADD_LOCATION',
	ADD_STORE_GOOD: 'ADD_STORE_GOOD',

	DELETE_DISTRIBUTOR: 'DELETE_DISTRIBUTOR',
	DELETE_PRODUCT: 'DELETE_PRODUCT',
	DELETE_PREPPED_PRODUCT: 'DELETE_PREPPED_PRODUCT',
	DELETE_LOCATION: 'DELETE_LOCATION',
	DELETE_STORE_GOOD: 'DELETE_STORE_GOOD',

	UPDATE_LOCATION_ROW_ORDER: 'UPDATE_LOCATION_ROW_ORDER',
	UPDATE_AMOUNT_IN_STOCK: 'UPDATE_AMOUNT_IN_STOCK'
}