export default {
	GET_PRODUCTS: 'GET_PRODUCTS',
	ADD_STORE: 'ADD_STORE',
	GET_STORE_TYPES: 'GET_STORE_TYPES',
	GET_CATEGORIES: 'GET_CATEGORIES',
	GET_COUNT_BIES: 'GET_COUNT_BIES',
	GET_DISTRIBUTORS: 'GET_DISTRIBUTORS',
}